#!/bin/bash

export TMUX_TMPDIR="/tmp/clerk/tmux"

if [[ ! -d "${TMUX_TMPDIR}" ]]; then
  mkdir -p "${TMUX_TMPDIR}"
fi

tmux has-session -t music
if [ $? != 0 ]; then
  tmux -f /etc/clerk/tmux.conf new-session -s music -n albums -d 'clerk_fzf --albums'
#  tmux send-keys -t music 'clerk_fzf --albums' C-m
  tmux new-window -t music -n tracks 'clerk_fzf --tracks'
#  tmux send-keys -t music 'clerk_fzf --tracks' C-m
  tmux new-window -t music -n latest 'clerk_fzf --latest'
#  tmux send-keys -t music 'clerk_fzf --latest' C-m
  tmux new-window -t music -n queue 'ncmpcpp'
#  tmux send-keys -t music 'ncmpcpp' C-m
fi

tmux attach -t music
