#!/bin/bash

TMUX_TMPDIR="/tmp/clerk/tmux"

screen=$(tmux list-panes -F "#W")

if [[ $1 == "--create-caches" ]]; then
  if [[ $animation == "1" ]]; then
    tmux new-session -s notify -n 'Updating Cache Files. Please wait a moment' -d 'sl'
  else
    tmux new-session -s notify -n 'Updating Cache Files. Please wait a moment' -d 'sh'
  fi
  tmux switchc -t notify
  clerk_fzf --update &
  pid=$!
  wait $pid
fi

tmux new-session -s music2 -n albums -d 'clerk_fzf --albums'
tmux new-window -t music2 -n tracks 'clerk_fzf --tracks'
tmux new-window -t music2 -n latest 'clerk_fzf --latest'
tmux new-window -t music2 -n queue 'ncmpcpp'

tmux rename-session -t music music_old
tmux rename-session -t music2 music
tmux switchc -t music
tmux findw -t music ${screen}
tmux kill-session -t music_old

if [[ $1 == "--create-caches" ]]; then
  tmux kill-session -t notify
fi
