#!/bin/bash

# default tmux config
tmux_config="/etc/clerk/tmux.conf"

# read global config
if [[ -f "/etc/clerk_fzf.conf" ]]; then
  source /etc/clerk_fzf.conf
fi
 
# create config dir, if needed
if [[ ! -d $HOME/.config/clerk ]]; then
  mkdir $HOME/.config/clerk
fi
 
# read user config
if [[ -f "$HOME/.config/clerk/clerk_fzf.conf" ]]; then
  source $HOME/.config/clerk/clerk_fzf.conf
fi

# export MPD_HOST
if [[ -n $mpd_host ]]; then
  if [[ -n $mpd_password ]]; then
    export MPD_HOST="${mpd_password}@${mpd_host}"
  else
    export MPD_HOST="${mpd_host}"
  fi
fi
 
if [[ -n $mpd_port ]]; then
  ┆ export MPD_PORT="${mpd_port}"
fi


export TMUX_TMPDIR="/tmp/clerk/tmux"

if [[ ! -d "${TMUX_TMPDIR}" ]]; then
  mkdir -p "${TMUX_TMPDIR}"
fi

main() {
  tmux has-session -t music
  if [ $? != 0 ]; then
    tmux -f "${tmux_config}" new-session -s music -n albums -d 'clerk_fzf --albums'
    tmux new-window -t music -n tracks 'clerk_fzf --tracks'
    tmux new-window -t music -n latest 'clerk_fzf --latest'
    tmux new-window -t music -n queue 'ncmpcpp'
  fi
  tmux attach -t music
}


if [[ $1 == "--help" || $1 == "-h" ]]; then
  echo "clerk: MPD Interface using fzf and tmux"
  echo "Copyright © 2016 Rasmus Steinke"
  echo ""
  echo "--help, -h    this help message"
  echo "--kill        kill running clerk sessions"
elif [[ $1 == "--kill" ]]; then
  tmux kill-session -t music
else
  main
fi


